-- Botica M&LL
-- Base de datos para las pantallas: Login, Dashboard de Almacen,
-- Inventario/Lotes y Kardex de Entrada.
-- Entidad nucleo: lote.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombres text not null,
  apellidos text not null,
  rol text not null default 'almacen',
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.proveedores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  ruc varchar(11) unique,
  telefono text,
  email text,
  direccion text,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  categoria_id bigint references public.categorias(id) on update cascade on delete restrict,
  codigo text not null unique,
  nombre text not null,
  principio_activo text,
  concentracion text,
  presentacion text not null,
  unidad_medida text not null default 'unidad',
  stock_minimo integer not null default 0 check (stock_minimo >= 0),
  precio_venta numeric(10,2) not null default 0 check (precio_venta >= 0),
  requiere_receta boolean not null default false,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.lotes (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on update cascade on delete restrict,
  proveedor_id bigint references public.proveedores(id) on update cascade on delete set null,
  codigo_lote text not null unique,
  cantidad integer not null check (cantidad >= 0),
  fecha_vencimiento date not null,
  precio_compra numeric(10,2) not null default 0 check (precio_compra >= 0),
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.movimientos_kardex (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.productos(id) on update cascade on delete set null,
  lote_id bigint references public.lotes(id) on update cascade on delete set null,
  usuario_id uuid references public.profiles(id) on update cascade on delete set null,
  tipo text not null check (tipo in ('entrada', 'salida', 'ajuste')),
  cantidad integer not null check (cantidad > 0),
  motivo text not null,
  costo_unitario numeric(10,2) not null default 0 check (costo_unitario >= 0),
  fecha timestamptz not null default now()
);

create or replace function public.set_actualizado_en()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

drop trigger if exists trg_lotes_actualizado_en on public.lotes;
create trigger trg_lotes_actualizado_en
before update on public.lotes
for each row
execute function public.set_actualizado_en();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nombres, apellidos, rol)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nombres', 'Usuario'),
    coalesce(new.raw_user_meta_data->>'apellidos', 'M&LL'),
    coalesce(new.raw_user_meta_data->>'rol', 'almacen')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.categorias enable row level security;
alter table public.proveedores enable row level security;
alter table public.productos enable row level security;
alter table public.lotes enable row level security;
alter table public.movimientos_kardex enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "categorias_crud_authenticated" on public.categorias;
create policy "categorias_crud_authenticated"
on public.categorias for all
to authenticated
using (true)
with check (true);

drop policy if exists "proveedores_crud_authenticated" on public.proveedores;
create policy "proveedores_crud_authenticated"
on public.proveedores for all
to authenticated
using (true)
with check (true);

drop policy if exists "productos_crud_authenticated" on public.productos;
create policy "productos_crud_authenticated"
on public.productos for all
to authenticated
using (true)
with check (true);

drop policy if exists "lotes_crud_authenticated" on public.lotes;
create policy "lotes_crud_authenticated"
on public.lotes for all
to authenticated
using (true)
with check (true);

drop policy if exists "movimientos_crud_authenticated" on public.movimientos_kardex;
create policy "movimientos_crud_authenticated"
on public.movimientos_kardex for all
to authenticated
using (true)
with check (true);

create or replace view public.v_lotes_inventario as
select
  l.id,
  l.codigo_lote,
  l.cantidad,
  l.fecha_vencimiento,
  l.precio_compra,
  l.activo,
  p.codigo as producto_codigo,
  p.nombre as producto_nombre,
  p.stock_minimo,
  c.nombre as categoria_nombre,
  pr.nombre as proveedor_nombre,
  case
    when l.fecha_vencimiento <= current_date + interval '30 days' then 'Por vencer'
    when l.cantidad <= p.stock_minimo then 'Stock bajo'
    else 'Disponible'
  end as estado_lote
from public.lotes l
join public.productos p on p.id = l.producto_id
left join public.categorias c on c.id = p.categoria_id
left join public.proveedores pr on pr.id = l.proveedor_id;

insert into public.categorias (nombre, descripcion)
values
  ('Tabletas', 'Medicamentos solidos en tabletas'),
  ('Capsulas', 'Medicamentos solidos en capsulas'),
  ('Jarabes', 'Medicamentos liquidos'),
  ('Insumos', 'Material medico e insumos')
on conflict (nombre) do nothing;

insert into public.proveedores (nombre, ruc, telefono, email, direccion)
values
  ('Drogueria Alfa', '20111111111', '044-555111', 'ventas@drogueriaalfa.pe', 'Trujillo'),
  ('Medifarma S.A.', '20222222222', '044-555222', 'contacto@medifarma.pe', 'Lima'),
  ('Farmaindustria', '20333333333', '044-555333', 'pedidos@farmaindustria.pe', 'Trujillo')
on conflict (ruc) do nothing;

insert into public.productos (
  categoria_id,
  codigo,
  nombre,
  principio_activo,
  concentracion,
  presentacion,
  unidad_medida,
  stock_minimo,
  precio_venta,
  requiere_receta
)
values
  ((select id from public.categorias where nombre = 'Tabletas'), 'MED-001', 'Paracetamol 500 mg', 'Paracetamol', '500 mg', 'Caja x 100 tabletas', 'tableta', 80, 0.50, false),
  ((select id from public.categorias where nombre = 'Capsulas'), 'MED-018', 'Amoxicilina 500 mg', 'Amoxicilina', '500 mg', 'Caja x 100 capsulas', 'capsula', 60, 1.20, true),
  ((select id from public.categorias where nombre = 'Insumos'), 'INS-044', 'Jeringas 5 ml', 'No aplica', '5 ml', 'Bolsa x 100 unidades', 'unidad', 40, 0.80, false),
  ((select id from public.categorias where nombre = 'Tabletas'), 'MED-031', 'Ibuprofeno 400 mg', 'Ibuprofeno', '400 mg', 'Caja x 100 tabletas', 'tableta', 50, 0.70, false)
on conflict (codigo) do nothing;

insert into public.lotes (
  producto_id,
  proveedor_id,
  codigo_lote,
  cantidad,
  fecha_vencimiento,
  precio_compra
)
values
  ((select id from public.productos where codigo = 'MED-001'), (select id from public.proveedores where ruc = '20111111111'), 'L-PCT500', 340, '2027-12-15', 0.18),
  ((select id from public.productos where codigo = 'MED-018'), (select id from public.proveedores where ruc = '20111111111'), 'L-AMX500', 96, '2027-04-20', 0.40),
  ((select id from public.productos where codigo = 'INS-044'), (select id from public.proveedores where ruc = '20333333333'), 'L-JER5', 22, '2026-09-30', 0.35),
  ((select id from public.productos where codigo = 'MED-031'), (select id from public.proveedores where ruc = '20222222222'), 'L-IBU400', 18, '2028-02-10', 0.25)
on conflict (codigo_lote) do nothing;

insert into public.movimientos_kardex (producto_id, lote_id, tipo, cantidad, motivo, costo_unitario)
select producto_id, id, 'entrada', cantidad, 'Carga inicial de inventario', precio_compra
from public.lotes
where codigo_lote in ('L-PCT500', 'L-AMX500', 'L-JER5', 'L-IBU400')
and not exists (
  select 1
  from public.movimientos_kardex mk
  where mk.lote_id = lotes.id
  and mk.motivo = 'Carga inicial de inventario'
);
